Controllers/PlantController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;

using GardenIt.Models;
using GardenIt.Models.ViewModels;
using GardenIt.Models.Engine;

namespace GardenIt.Controllers
{
    [Authorize]
    public class PlantController : Controller
    {
        private readonly Garden _garden;
        private UserManager<IdentityUser> _userManager;
        private readonly IWebHostEnvironment _hostEnv;
        private readonly static string DEFAULT_IMAGE_NAME = "default.png"; 

        public PlantController(Garden garden, UserManager<IdentityUser> userManager, IWebHostEnvironment hostEnv)
        {
            _garden = garden;
            _userManager = userManager;
            _hostEnv = hostEnv;
        }

        public IActionResult Index()
        {
            var result = _garden.GetAllPlants(UserId());
            return View(result);
        }

        public IActionResult Details(Guid id)
        {
            var result = _garden.GetPlant(id, UserId());
            return View(result);
        }

        public IActionResult Create() {
            ViewBag.IsEditing = false;
            return View("Form");  
        }

        [HttpPost]
        public IActionResult Create(PlantViewModel plantViewModel) {
            if (ModelState.IsValid) {
                string imageName = SaveAndGenerateImageName(plantViewModel.ImageFile);
                var newPlant = new Plant() {
                    Id = Guid.NewGuid(),
                    UserId = UserId(),
                    Name = plantViewModel.Name,
                    Type = plantViewModel.Type,
                    DateAdded = DateTime.Now,
                    DaysBetweenWatering = plantViewModel.DaysBetweenWatering,
                    Notes = plantViewModel.Notes,
                    ImageName = imageName,
                    Waterings = new List<Watering>()
                };
                _garden.CreatePlant(newPlant);
                return RedirectToAction("Index");
            }

            return View("Form");

        }

        public IActionResult Edit(Guid id) {
            var existingPlant = _garden.GetPlant(id, UserId());

            var plantViewModel = new PlantViewModel() {
                Id = id,
                Name = existingPlant.Name,
                Type = existingPlant.Type,
                DaysBetweenWatering = existingPlant.DaysBetweenWatering,
                Notes = existingPlant.Notes,
                ImageName = existingPlant.ImageName,
            };

            ViewBag.IsEditing = true;
            return View("Form", plantViewModel);
        }

        [HttpPost]
        public IActionResult Edit(PlantViewModel updatedPlant) {
            if (ModelState.IsValid) {
                string imageName = SaveAndGenerateImageName(updatedPlant.ImageFile);

                var existingPlant = _garden.GetPlant(updatedPlant.Id.Value, UserId());
                var plant = new Plant() {
                    Id = existingPlant.Id,
                    Name = updatedPlant.Name,
                    Type = updatedPlant.Type,
                    DaysBetweenWatering = updatedPlant.DaysBetweenWatering,
                    DateAdded = existingPlant.DateAdded,
                    Waterings = existingPlant.Waterings,
                    UserId = UserId(),
                    Notes = updatedPlant.Notes,
                    ImageName = imageName == DEFAULT_IMAGE_NAME ? existingPlant.ImageName : imageName
                };
                _garden.UpdatePlant(plant);
                return RedirectToAction("Details", new { id = existingPlant.Id});
            } else {
                ViewBag.IsEditing = true;
                return View("Form", updatedPlant);
            }
        }

        [HttpPost]
        public IActionResult Delete(Guid id) {
            _garden.DeletePlant(id, UserId());
            return RedirectToAction("Index");
        }


        public IActionResult Water(Guid id) {
            _garden.WaterPlant(id, UserId());
            return RedirectToAction("Details", new { id });
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private Guid UserId() {
            string stringUserId = _userManager.GetUserId(User);
            return Guid.Parse(stringUserId);
        }

        private string SaveAndGenerateImageName(IFormFile image) {
            string wwwRootPath = _hostEnv.WebRootPath;

            if (image != null) {
                string filename = Path.GetFileNameWithoutExtension(image.FileName);
                string dateString = DateTime.Now.ToString("yymmssfff");
                string ext = Path.GetExtension(image.FileName);
                string imageName = filename + dateString + ext;
                string path = Path.Combine(wwwRootPath + "/image/", imageName);
                var fileStream = new FileStream(path, FileMode.Create);
                image.CopyTo(fileStream);
                return imageName;
            } else {
                return DEFAULT_IMAGE_NAME;
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GardenIt</title>
    <link rel="icon" href="~/image/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3 my-bg">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Plant" asp-action="Index">
                    <img src="~/image/main_image.png" width="30" height="26" alt="">
                    <span class="text-light">
                         &nbsp;
                        GardenIt
                    </span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @* <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul> *@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-light my-bg">
        <div class="container">
            &copy; 2020 - GardenIt - <a class="text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

<script>
$(document).ready( function () {
    $('.watering-table').DataTable({
        "searching": false,   // Search Box will Be Disabled
        "ordering": false,    // Ordering (Sorting on Each Column)will Be Disabled
        "info": true,         // Will show "1 to n of n entries" Text at bottom
        "lengthChange": false // Will Disabled Record number per page
    });
});
</script>